# Copyright (C) 2024 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

- name: DIALER installation and configuration
  hosts: 
    - omnileads_dialer
    - omnileads_aio
  tags:
    - install
    - dialer
  tasks:

  - name: DIALER Set environment variables for this installation
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "0664"
      owner: "omnileads"
      group: "omnileads"
    loop:
      - { src: "{{ dialer_repo_path }}templates/dialer.env", dest: "/etc/default/dialer.env" }
    tags:
      - install
      - upgrade
      - update

  - name: DIALER template stop worker containers script
    template: 
      src: "{{ dialer_repo_path }}templates/stop_workers.sh"
      dest: /usr/local/bin/dialer_stop_workers.sh
      mode: 755
    tags:
      - upgrade
      - update

  - name: DIALER postgres DB Ensure PostgreSQL database exists
    postgresql_db:
      name: omnidialer
      owner: "{{ postgres_user }}"
      login_host: "{{ postgres_host }}"
      login_password: "{{ postgres_password }}"
      login_user: "{{ postgres_user }}"
      port: "{{ postgres_port }}"
      maintenance_db: "{{ postgres_maintenance_db }}"
      state: present
    tags:
      - install  

  - name: DIALER postgres DB template omnidialer tables
    template: 
      src: "{{ dialer_repo_path }}templates/omnidialer.sql"
      dest: /var/tmp/omnidialer.sql
      mode: 755
    tags:
      - upgrade
      - update

  - name: DIALER postgres DB generate file_timestamp for container DB creator
    set_fact:
      file_timestamp: "{{ ansible_date_time.epoch }}"
    tags:
      - install  

  - name: DIALER postgres DB create omnidialer
    shell: "podman run --name omnidialer_createdb_{{ file_timestamp }} --network=host --env-file /etc/default/django.env --volume=/var/tmp/omnidialer.sql:/var/tmp/omnidialer.sql --rm {{ omnileads_img }} psql -U {{ postgres_user }} -d omnidialer -f /var/tmp/omnidialer.sql"
    tags:
      - install  

  - name: DIALER Copy systemd services
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    loop:
      # - { src: "{{ dialer_repo_path }}templates/postgresql.service", dest: "/etc/systemd/system/dialer_postgresql.service" }
      # - { src: "{{ dialer_repo_path }}templates/redis.service", dest: "/etc/systemd/system/dialer_redis.service" }
      - { src: "{{ dialer_repo_path }}templates/gearman.service", dest: "/etc/systemd/system/dialer_gearman.service" }
      - { src: "{{ dialer_repo_path }}templates/listener.service", dest: "/etc/systemd/system/dialer_listener.service" }
      - { src: "{{ dialer_repo_path }}templates/asterisk.service", dest: "/etc/systemd/system/dialer_asterisk.service" }
      - { src: "{{ dialer_repo_path }}templates/dialplan.service", dest: "/etc/systemd/system/dialer_dialplan.service" }
      - { src: "{{ dialer_repo_path }}templates/scheduler.service", dest: "/etc/systemd/system/dialer_scheduler.service" }
      - { src: "{{ dialer_repo_path }}templates/listener.service", dest: "/etc/systemd/system/dialer_listener.service" }
      - { src: "{{ dialer_repo_path }}templates/worker.service", dest: "/etc/systemd/system/dialer_workers.service" }
      - { src: "{{ dialer_repo_path }}templates/api.service", dest: "/etc/systemd/system/dialer_api.service" }
    tags:
      - install
      - upgrade
      - update

  - name: DIALER Pull images
    command: podman pull --quiet {{ item.image }}
    register: podman_pull_result
    until: podman_pull_result is success
    loop:
      - { image: "{{ gearman_img }}"}
      - { image: "{{ dialer_api_img }}"}
      - { image: "{{ dialer_worker_img }}"}
      - { image: "{{ dialer_listener_img }}"}
      - { image: "{{ dialer_scheduler_img }}"}
      - { image: "{{ dialer_asterisk_img }}"}
      - { image: "{{ dialer_dialplan_img }}"}
    tags:
      - install
      - upgrade
      - update

  - name: DIALER Enable and start systemd services
    systemd:
      name: "{{ item.name }}"
      state: started
      enabled: yes
      daemon_reload: yes
    loop:
      - { name: 'dialer_gearman.service' }
      - { name: 'dialer_asterisk.service' }
      - { name: 'dialer_dialplan.service' }    
      - { name: 'dialer_workers.service' }    
      - { name: 'dialer_scheduler.service' }    
      - { name: 'dialer_listener.service' }    
      - { name: 'dialer_api.service' }    
    when: omnileads_ha is not defined
    tags:
      - install
      - upgrade
