---
- name: UPGRADE_2X Restore PostgreSQL desde backup (delegado al rol backup)
  ansible.builtin.import_role:
    name: backup
    tasks_from: restore_dbs
  when: (group_names | intersect(upgrade_from_2X_target_host_groups)) | length > 0
