networks:
  omnileads:
    ipam:
      driver: default
      config:
        - subnet: "${SUBNET}"

volumes:
  postgresql:
  redis:
  minio:
  django_static:
  django_callrec_zip:
  asterisk_callrec:
  asterisk_sounds:
  asterisk_conf:
  dialer-postgresql: 
  
services:

  uwsgi:
    depends_on:
      django-commands:
        condition: service_completed_successfully
        required: true
      redis:
        condition: service_healthy
        required: true
      acd:
        condition: service_healthy
        required: true 
    dns: 8.8.8.8
    env_file: .env
    environment:
      - DJANGO_ALLOW_ASYNC_UNSAFE=true
      - CRON_ENABLE=false
      - DJANGO_SETTINGS_MODULE=ominicontacto.settings.production
      - KAMAILIO_HOSTNAME=${KAMAILIO_WEBRTC_HOSTNAME}
      - KAMAILIO_PORT=${KAMAILIO_WEBRTC_SIP_PORT}
    image: ${OMLAPP_IMG}
    command: /opt/omnileads/bin/init_uwsgi.sh
    networks:
      - omnileads
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL -o /dev/null http://${DJANGO_HOSTNAME}:${DJANGO_PORT:-8099}/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s  
    privileged: true
    restart: on-failure
    stdin_open: true
    stop_grace_period: 30s
    tty: true
    working_dir: /opt/omnileads/ominicontacto
    volumes:
      - django_static:/opt/omnileads/static
      - django_callrec_zip:/opt/omnileads/asterisk/var/spool/asterisk/monitor

  django-commands:
    depends_on:
      redis:
        condition: service_healthy
        required: true      
    dns: 8.8.8.8
    env_file: .env
    image: ${OMLAPP_IMG}
    command: /opt/omnileads/bin/django_commands.sh
    networks:
      - omnileads
    privileged: true
    stdin_open: true
    stop_grace_period: 30s
    tty: true
    working_dir: /opt/omnileads/ominicontacto
    volumes:
      - django_static:/opt/omnileads/static
      - django_callrec_zip:/opt/omnileads/asterisk/var/spool/asterisk/monitor

  daphne:
    depends_on:
      redis:
        condition: service_healthy
        required: true    
    dns: 8.8.8.8
    env_file: .env
    environment:
      - DAPHNE_ENABLE=True
      - DJANGO_HOSTNAME=${DAPHNE_HOSTNAME:-daphne}
      - DAPHNE_PORT=${DAPHNE_PORT:-8098}
    image: ${OMLAPP_IMG}
    command: /opt/omnileads/bin/init_daphne.sh
    networks:
      - omnileads 
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsSL -o /dev/null http://${DAPHNE_HOSTNAME}:${DAPHNE_PORT:-8098}/ || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 60s 
    privileged: true
    restart: on-failure
    stdin_open: true
    stop_grace_period: 1m30s
    tty: true
    working_dir: /opt/omnileads/ominicontacto

  cronos:
    depends_on:
      acd:
        condition: service_healthy
        required: true    
      redis:
        condition: service_healthy
        required: true    
    dns: 8.8.8.8
    env_file: .env
    environment:
      - UWSGI_PORT=8097
      - DJANGO_HOSTNAME=omlcron
    image: ${OMLAPP_IMG}
    command: /opt/omnileads/bin/docker-entrypoint.sh
    networks:
      - omnileads
    privileged: true
    restart: on-failure
    stdin_open: true
    stop_grace_period: 1m30s
    tty: true
    working_dir: /opt/omnileads

  background-callrec-tasks:
    image: ${OMLAPP_IMG}
    depends_on:
      redis:
        condition: service_healthy
        required: true  
    dns: 8.8.8.8
    env_file: .env
    command: /opt/omnileads/bin/init_worker_bgtasks.sh
    networks:
      - omnileads
    privileged: true
    restart: on-failure
    stdin_open: true
    stop_grace_period: 30s
    tty: true
    working_dir: /opt/omnileads/ominicontacto

  background-dialer-tasks:
    image: ${OMLAPP_IMG}
    depends_on:
      redis:
        condition: service_healthy
        required: true  
    dns: 8.8.8.8
    env_file: .env
    command: python manage.py omnidialer_events_listener
    networks:
      - omnileads
    privileged: true
    restart: on-failure
    stdin_open: true
    stop_grace_period: 30s
    tty: true
    working_dir: /opt/omnileads/ominicontacto

  nginx:
    image: ${OMLNGINX_IMG}
    depends_on:
      uwsgi:
        condition: service_healthy
        required: true
      daphne:
        condition: service_started
        required: true
      kamailio-webrtc:
        condition: service_started
        required: true    
      websockets:
        condition: service_started
        required: true   
    dns: 8.8.8.8
    environment:
      - ENV=prodenv
      - TZ=${TZ}
      - DJANGO_HOSTNAME=${DJANGO_HOSTNAME}
      - WSGI_PORT=${UWSGI_PORT}
      - DAPHNE_HOSTNAME=${DAPHNE_HOSTNAME}
      - ASGI_PORT=${UWSGI_PORT}
      - KAMAILIO_HOSTNAME=${KAMAILIO_WEBRTC_HOSTNAME}
      - KAMAILIO_PORT=14443
      - WEBSOCKETS_HOSTNAME=${WEBSOCKET_HOSTNAME}
      - WEBSOCKETS_PORT=8000
      - CALLREC_DEVICE=${CALLREC_DEVICE}
      - S3_ENDPOINT=${S3_ENDPOINT_MINIO}
      - WEBUI_MODE=rproxy
      - WALLBOARD_WEBUI_HOST=${KAMAILIO_WEBRTC_HOSTNAME}
    networks:
      - omnileads
    privileged: true
    ports:
      - ${NGINX_EXT_PORT}:443/tcp
    restart: on-failure
    stop_grace_period: 15s
    volumes:
      - django_static:/opt/omnileads/static
      - django_callrec_zip:/opt/omnileads/asterisk/var/spool/asterisk/monitor

  fastagi:
    depends_on:
      redis:
        condition: service_healthy
        required: true      
    image: ${OMLFASTAGI_IMG}
    command: python /app/fastagi.py
    environment:
      - DIALER_AMD_ENDPOINT=${DIALER_API_HOST}
      - PGHOST=${OML_HOSTNAME}
      - PGPORT=${POSTGRES_EXT_PORT}
      - PGUSER=${POSTGRES_USER}
      - PGDATABASE=${POSTGRES_DB}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOSTNAME=${OML_HOSTNAME}
      - REDIS_PORT=${REDIS_EXT_PORT}
      - OMNILEADS_HOSTNAME=${NGINX_HOSTNAME}      
      - TZ=${TZ}
    restart: on-failure
    networks:
      - omnileads      
    # healthcheck:
    #   test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.connect(('localhost', 4573)); s.close()"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s   
    ports:
      - ${FASTAGI_EXT_BIND_IP:-0.0.0.0}:${FASTAGI_EXT_PORT:-4573}:4573/tcp

  ami:
    image: ${OMLAMI_IMG}
    depends_on:
      acd:
        condition: service_healthy
        required: true    
      redis:
        condition: service_healthy
        required: true    
    environment:
      - TZ=${TZ}
      - ASTERISK_HOSTNAME=${ACD_HOSTNAME}
      - AMI_USER=${ACD_AMI_USER}
      - AMI_PASSWORD=${ACD_AMI_PASSWORD}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
    restart: on-failure    
    networks:
      - omnileads

  acd-config-generator:
    image: ${OMLACD_RETRIEVE_CONF_IMG}
    depends_on:
      websockets:
        condition: service_started
        required: true
    dns: 8.8.8.8
    environment:
      - TZ=${TZ}
      - ASTERISK_LOCATION=
      - ARI_HOST=${ACD_HOSTNAME}
      - ARI_USER=${ACD_AMI_USER}
      - ARI_PASS=${ACD_AMI_PASSWORD}
      - OMNILEADS_HOSTNAME=${NGINX_HOSTNAME}
    networks:
      - omnileads
    privileged: true
    restart: on-failure
    stop_grace_period: 10s
    volumes:      
      - asterisk_conf:/home/omnileads/astconf
      - asterisk_sounds:/home/omnileads/sounds

  acd:
    image: ${OMLACD_IMG}
    depends_on:
      fastagi:
        condition: service_started
        required: true
      gearman:
        condition: service_healthy
        required: true
    network_mode: host
    environment:
      - AMI_USER=${ACD_AMI_USER}
      - AMI_PASSWORD=${ACD_AMI_PASSWORD}
      - CALLREC_SPLIT_CHANNELS=${ACD_CALLREC_SPLIT}
      - DIALER_HOST=${DIALER_SIP_ADDR}
      - ENV=${ENV}
      - FASTAGI=${OML_HOSTNAME}      
      - HOMER_ENABLE=${HOMER_ENABLE}
      - HOMERHOST=${HOMER_HOSTNAME}
      - HOMERPORT=${HOMER_PORT}
      - GEARMAN_HOST=${OML_HOSTNAME}
      - SIP_NAT_IPADDR=${VOIP_NAT}
      - RTP_PORT_MAX=${ACD_RTP_PORT_MAX}
      - RTP_PORT_MIN=${ACD_RTP_PORT_MIN}
    healthcheck:
      test: ["CMD-SHELL", "asterisk -rx 'core show channels' | grep -q 'active channels' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    privileged: true
    restart: on-failure
    stop_grace_period: 30s
    volumes:
      - asterisk_callrec:/var/spool/asterisk/monitor/
      - asterisk_conf:/etc/asterisk/retrieve_conf
      - asterisk_sounds:/var/lib/asterisk/sounds
      #- ../.custom_conf/google_credential.json:/tmp/google_credential.json
      #- ../.custom_conf/oml_extensions_custom.conf:/etc/asterisk/oml_extensions_custom.conf
    working_dir: /etc/asterisk

  callrec-processor:
    image: ${OMLINTERACTION_PROC_IMG}
    depends_on:
      gearman:
        condition: service_healthy
        required: true    
      acd:
        condition: service_healthy
        required: true
    dns: 8.8.8.8
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - CALLREC_DEVICE=${CALLREC_DEVICE}      
      - GEARMAN_HOST=${GEARMAN_HOSTNAME}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ENDPOINT=${S3_ENDPOINT_MINIO}      
      - TZ=${TZ}
    networks:
      - omnileads
    privileged: true
    restart: on-failure
    stop_grace_period: 10s
    command: python /app/app.py
    volumes:
      - asterisk_callrec:/var/spool/asterisk/monitor/
  
  call-logger:
    image: ${OMLCHAN_TEL_LOGGER_IMG}
    depends_on:
      gearman:
        condition: service_healthy
        required: true    
    dns: 8.8.8.8
    environment:
      - GEARMAN_HOST=${GEARMAN_HOSTNAME}
      - PGHOST=${POSTGRES_HOSTNAME}
      - PGPORT=${POSTGRES_PORT}
      - PGUSER=${POSTGRES_USER}
      - PGDATABASE=${POSTGRES_DB}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_PORT=${REDIS_PORT}  
      - TZ=${TZ}
    networks:
      - omnileads
    privileged: true
    restart: on-failure
    stop_grace_period: 10s
    command: python /app/app.py

  kamailio-webrtc:
    image: ${OMLKAM_IMG}
    depends_on:
      redis:
        condition: service_healthy
        required: true    
      acd:
        condition: service_healthy
        required: true    
      rtpengine:
        condition: service_started
        required: true    
    dns: 8.8.8.8
    environment:
      - AUTHEPH_SK=${AUTHEPH_SK}
      - ASTERISK_HOSTNAME=${ACD_HOSTNAME}
      - KAMAILIO_CERTS_LOCATION=${KAMAILIO_CERTS_LOCATION}
      - KAMAILIO_HOSTNAME=${KAMAILIO_WEBRTC_HOSTNAME}
      - REDIS_HOSTNAME=${OML_HOSTNAME}
      - RTPENGINE_HOSTNAME=${RTPENGINE_HOSTNAME}
      - SHM_SIZE=${SHM_SIZE}
      - PKG_SIZE=${PKG_SIZE}
      - TZ=${TZ}
    network_mode: host
    privileged: true
    restart: on-failure
    stop_grace_period: 10s

  rtpengine:
    image: ${OMLRTPENGINE_IMG}
    network_mode: host
    environment:
      - ENV=docker
      - TZ=${TZ}
      - RTPENGINE_HOSTNAME=${RTPENGINE_HOSTNAME}
      - PUBLIC_IP=${RTPENGINE_HOSTNAME}
      - RTP_PORT_MIN=${RTPENGINE_RTP_PORT_MIN}
      - RTP_PORT_MAX=${RTPENGINE_RTP_PORT_MAX}
      - NG_BIND_UDP_PORT=${RTPENGINE_BIND_UDP_PORT}
    privileged: true
    restart: on-failure
    stop_grace_period: 10s
    # command: rtpengine --config-file /etc/rtpengine.conf   
    # volumes:
    #   - ../.custom_conf/rtpengine.conf:/etc/rtpengine.conf:ro

  websockets:
    tty: true
    image: ${OMLWS_IMG}
    depends_on:
      - redis
    environment:
      - BIND_ADDRESS=0.0.0.0:8000
      - EVENT_LOOP=uvloop
      - LOGGERS=${WEBSOCKET_LOGGER}
      - REDIS_HOST=${WEBSOCKET_REDIS_HOSTNAME}
      - PYTHONUNBUFFERED=1
    networks:
      - omnileads
    stop_grace_period: 30s  

  redis:
    image: ${REDIS_IMG}
    dns: 8.8.8.8
    environment:
      - TZ=${TZ}
      - BIND_IP=0.0.0.0
    networks:
      - omnileads
    ports:
      - ${REDIS_EXT_BIND_IP:-0.0.0.0}:${REDIS_EXT_PORT}:6379/tcp
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5  
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - redis:/data
      
  gearman:
    image: ${GEARMAN_IMG}
    ports:
      - ${GEARMAN_EXT_BIND_IP:-0.0.0.0}:${GEARMAN_EXT_PORT:-4730}:4730/tcp
    networks:
      - omnileads
    command: gearmand -t 1
    healthcheck:
      test: ["CMD-SHELL", "gearadmin --status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

############################# Dialer Stack #######################################################

  dialer-api:
    build:
      target: run
      context: ./interface/src
    image: ${API_IMG}
    ports:
      - ${DIALER_API_EXT_BIND_IP:-0.0.0.0}:${DIALER_API_EXT_PORT:-1440}:1440/tcp
    networks:
      - omnileads
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - WEBSOCKET_SERVER=${DIALER_DCHANNELS_URL}

  scheduler:
    build:
      context: ./scheduler/src
    image: ${SCHEDULER_IMG}
    ports:
      - ${DIALER_SCHEDULER_EXT_BIND_IP:-0.0.0.0}:${DIALER_SCHEDULER_EXT_PORT:-1441}:1441/tcp
    networks:
      - omnileads
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    environment:
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - REDIS_DIALER_SERVER=${DIALER_REDIS_SERVER}
      - REDIS_DIALER_PORT=${DIALER_REDIS_PORT}
      - TZ=${TZ}

  listener:
    build:
      context: ./websocket_ari/src
    image: ${LISTENER_IMG}
    networks:
      - omnileads
    tty: true
    stdin_open: true
    environment:
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - ASTERISK_APP_DIALER=call_manager_dialer
      - TZ=${TZ}
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
    depends_on:
      - dialer-postgresql
      - start-campaign
  start-campaign:
    build:
      context: ./workers/handle-campaign/src
    image: ${WORKER_IMG}
    networks:
      - omnileads
    tty: true
    stdin_open: true
    environment:
      - GEARMAN_JOBS=start-campaign
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}
    depends_on:
      - dialer-postgresql

  process-contact-worker:
    image: ${WORKER_IMG}
    deploy:
      replicas: ${DIALER_PROCESS_CONTACT_REPLICAS}
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    environment:
      - GEARMAN_JOBS=process-contact
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}
    depends_on:
      - dialer-postgresql
    networks:
      - omnileads

  process-campaign-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    deploy:
      replicas: ${DIALER_PROCESS_CAMPAIGN_REPLICAS}
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    environment:
      - GEARMAN_JOBS=process-campaign
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}
    networks:
      - omnileads

  create-campaign-worker:
    image: ${WORKER_IMG}
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=create-campaign
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}
    networks:
      - omnileads

  resume-campaign-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=resume-campaign
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}      
    networks:
      - omnileads

  edit-campaign-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=edit-campaign
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}      
    networks:
      - omnileads

  stop-campaign-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=stop-campaign
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}
    networks:
      - omnileads

  pause-campaign-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=pause-campaign
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}
    networks:
      - omnileads

  delete-campaign-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=delete-campaign
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}      
    networks:
      - omnileads

  process-event-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    deploy: 
        replicas: ${DIALER_PROCESS_CONTACT_REPLICAS}
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    environment:
      - GEARMAN_JOBS=process-event
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}      
    networks:
      - omnileads

  schedule-contact-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=schedule-contact
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}      
    networks:
      - omnileads

  send-reports-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=send-reports
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}      
    networks:
      - omnileads

  add-incidence-rule-disposition-worker:
    image: ${WORKER_IMG}
    tty: true
    stdin_open: true
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=add-incidence-rule-disposition
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}      
    networks:
      - omnileads

  change-database-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=change-database
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}
    networks:
      - omnileads

  create-incidence-rule-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=create-incidence-rule
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}
    networks:
      - omnileads

  delete-incidence-rule-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=delete-incidence-rule
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}
    networks:
      - omnileads

  update-incidence-rule-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=update-incidence-rule
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}    
    networks:
      - omnileads

  schedule-agenda:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=schedule-agenda
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}
    networks:
      - omnileads

  render-template:
    image: ${WORKER_IMG}
    env_file: .env
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=render-template
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}
    networks:
      - omnileads

  manage-dialer:
    image: ${WORKER_IMG}    
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=manage-dialer
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway           
      - POSTGRES_OML_SERVER=${POSTGRES_HOSTNAME}
      - POSTGRES_OML_PORT=${POSTGRES_PORT}
      - POSTGRES_OML_USER=${POSTGRES_USER}
      - POSTGRES_OML_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_SERVER=${DIALER_POSTGRES_SERVER}
      - POSTGRES_DIALER_PORT=${DIALER_POSTGRES_PORT}
      - POSTGRES_DIALER_USER=${DIALER_POSTGRES_USER}  
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DIALER_DB=${DIALER_POSTGRES_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${DIALER_PYTHON_LOGLEVEL}
    networks:
      - omnileads

  dialer-acd:
    build:
      context: ./asterisk/
    image: ${ASTERISK_IMG}
    environment:
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - OMLACD_SIP_SERVER=${ACD_DIALER_PJSIP_TRANSPORT}
      - PSTNGW_REGISTER=${DIALER_PSTNGW_REGISTER}
      - PSTNGW_SIP_AUTH=${DIALER_PSTNGW_AUTH}
      - PSTNGW_SIP_USER=${DIALER_PSTNGW_USER}
      - PSTNGW_SIP_PASS=${DIALER_PSTNGW_PASS}
    dns: 8.8.8.8
    network_mode: host
    privileged: true
    restart: on-failure
    stop_grace_period: 30s
    working_dir: /etc/asterisk

  dialer-dialplan:
    build:
      target: run
      context: ./dialplan/
    image: ${DIALPLAN_IMG}
    depends_on:
      - dialer-acd
    environment:
      - TZ=${TZ}
      - GEARMAN_HOST=${GEARMAN_HOSTNAME}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - REDIS_DB=${DIALER_REDIS_DB}
      - ASTERISK_HOST=${DIALER_ASTERISK_HOSTNAME}
      - ASTERISK_PORT=${DIALER_ASTERISK_ARI_PORT}
      - ASTERISK_USER=${ACD_AMI_USER}
      - ASTERISK_PASS=${ACD_AMI_PASSWORD}
      - ASTERISK_APP=call_manager
    restart: on-failure
    stop_grace_period: 30s    
    networks:
      - omnileads

  dialer-postgresql:
    dns: 8.8.8.8
    environment:
      - TZ=${TZ}
      - POSTGRES_USER=${DIALER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DIALER_POSTGRES_DB}
      - PGPORT=5433
    image: ${POSTGRES_IMG}
    networks:
      - omnileads
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - dialer-postgresql:/var/lib/postgresql/data
      - ./omnidialer.sql:/docker-entrypoint-initdb.d/init.sql