---
galaxy_info:
  role_name: upgrade_from_2X
  description: Tareas específicas migración OMniLeads 2.x a 3.x (systemd legacy + restore DBs).
  license: GPL-3.0-or-later
  min_ansible_version: "2.14"

dependencies: []
