# Copyright (C) 2024 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

---

- name: CHANTEL Logger Playbook
  hosts: 
    - omnileads_app
    - omnileads_aio
  tags:
    - asterisk
    - call_logger
  
  tasks:

  - name: Call Loggeer environment variables
    template:
      src: "{{ call_logger_repo_path }}templates/call_logger.env"
      dest: /etc/default/call_logger.env
      mode: 666
      owner: "{{ usuario }}"
      group: "{{ usuario }}"
    tags:
      - install
      - upgrade
      - update
      
  - name: Call logger Copy systemd service file
    template:
      src: "{{ call_logger_repo_path }}templates/call_logger.service"
      dest: /etc/systemd/system/call_logger.service
    tags:
      - install
      - upgrade
      - update
      
  - name: Call logger Pull image
    command: podman pull --quiet {{ call_logger_img }}
    register: podman_pull
    until: podman_pull is success
    tags:
      - install
      - upgrade
      - update

  - name: Call logger Enable and start systemd service HA scenary
    systemd:
      name: call_logger.service
      state: started
      enabled: no
      daemon_reload: yes
    tags:
      - install
      - upgrade
    when:       
      - omnileads_ha is defined  
      - ha_role == "main"
  
  - name: Call logger Enable and start systemd service
    systemd:
      name: call_logger.service
      state: started
      enabled: yes
      daemon_reload: yes
    tags:
      - install
      - upgrade
    when:       
      - omnileads_ha is not defined        

  - name: Call logger ReStart systemd service
    systemd:
      name: call_logger.service
      state: restarted
      enabled: yes
      daemon_reload: yes
    tags:
      - upgrade
      - restart
      - restart_core
    when:       
      - omnileads_ha is not defined