---
# Example of a cluster with the following tiers:
# - Data + Edge + Compute monolithic

all:
  children:
    cluster_instances:
      children:
        # Cluster AIT example — Data + Edge + Compute monolithic
        tenant_c:
          hosts:
            tenant_c_data:
              tenant_id: tenant_c_data
              ansible_host: "{{ vault_tenant_c_data_ansible_host }}"
              omni_ip_lan: 172.16.201.2
            tenant_c_edge:
              tenant_id: tenant_c_edge
              ansible_host: "{{ vault_tenant_c_edge_ansible_host }}"
              omni_ip_lan: 172.16.201.3
            tenant_c_node:
              tenant_id: tenant_c_node
              ansible_host: "{{ vault_tenant_c_node_ansible_host }}"
              omni_ip_lan: 172.16.201.4
          vars:
            tenant_id: tenant_c
            bucket_url: "{{ vault_tenant_c_bucket_url }}"
            bucket_name: "{{ vault_tenant_c_bucket_name }}"
            fqdn: "{{ vault_tenant_c_fqdn }}"
            itsp_nodes: "{{ vault_tenant_c_itsp_nodes }}"
            rtpengine_env: "{{ vault_tenant_c_rtpengine_env }}"
            kamailio_webrtc_iface: eth1

##########################################################
### All in One "AIO"
##########################################################
omnileads_aio:
  hosts:

##########################################################
### Cluster: Pod groups (a host can be in multiple groups)
##########################################################
data_statefull:
  hosts:
    tenant_c_data:

data_stateless:
  hosts:
    tenant_c_data:

edge:
  hosts:
    tenant_c_edge:

omlapp_web:
  hosts:
    tenant_c_node:

omlapp_workers:
  hosts:
    tenant_c_node:

dialer_workers:
  hosts:
    tenant_c_node:

acd:
  hosts:
    tenant_c_node:

callrec_processor:
  hosts:
    tenant_c_node:
