# Copyright (C) 2024 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

- name: OMniLeads Backup Playbook
  hosts: 
    - omnileads_app
    - omnileads_aio
  tags:
    - backup
  tasks:

    - name: BACKUP generate file_timestamp
      set_fact:
        file_timestamp: "{{ ansible_date_time.epoch }}"

    - name: BACKUP postgres OMniLeads DB .sql file and upload to the bucket
      shell: "podman run --name pgsql_bk_{{ file_timestamp }} --network=host --env-file /etc/default/backup.env -e BACKUP_FILENAME=backup/{{ tenant_id }}/pgsql-backup-{{ file_timestamp }}.sql --rm {{ backup_restore_img }} python backup.py"
      when:
      - omnileads_ha is not defined       

    - name: BACKUP postgres OMniLeads DB .sql file and upload to the bucket HA Scenary
      shell: "podman run --name pgsql_bk_{{ file_timestamp }} --network=host --env-file /etc/default/backup.env -e BACKUP_FILENAME=backup/{{ tenant_id }}/pgsql-backup-{{ file_timestamp }}.sql --rm {{ backup_restore_img }} python backup.py"
      when:
      - omnileads_ha is defined 
      - ha_role == "backup"  

    - name: BACKUP postgres OMniDialer DB .sql file and upload to the bucket
      shell: "podman run --name pgsql_bk_{{ file_timestamp }} --network=host --env-file /etc/default/backup.env -e SQL_DATABASE=omnidialer -e BACKUP_FILENAME=backup/{{ tenant_id }}/pgsql-backup-OMD-{{ file_timestamp }}.sql --rm {{ backup_restore_img }} python backup.py"
      when:
      - omnileads_ha is not defined
      - dialer_engine == "omnidialer"

    - name: BACKUP postgres OMniDialer DB .sql file and upload to the bucket HA Scenary
      shell: "podman run --name pgsql_bk_{{ file_timestamp }} --network=host --env-file /etc/default/backup.env -e SQL_DATABASE=omnidialer -e BACKUP_FILENAME=backup/{{ tenant_id }}/pgsql-backup-OMD-{{ file_timestamp }}.sql --rm {{ backup_restore_img }} python backup.py"
      when:
      - omnileads_ha is defined 
      - ha_role == "backup"  
      - dialer_engine == "omnidialer"
    